spring:
  config:
    activate:
      on-profile: docker

  kafka:
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# (DB 아직 안 붙이면 임시로 자동설정 제외 — 필요할 때만)
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  topics:
    notifications: notifications
    notifications-dlt: notifications.dlt
  push:
    enabled: true
