apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger-engine-service
  labels: { app: trigger-engine-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: trigger-engine-service } }
  template:
    metadata: { labels: { app: trigger-engine-service } }
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: ghcr.io/2ckdaks/trigger-engine-service:build-41
          ports:
            - containerPort: 8401
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: APP_TOPICS_NOTIFICATIONS
              value: notifications
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8401 }
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8401 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: trigger-engine-service
spec:
  selector: { app: trigger-engine-service }
  ports:
    - name: http
      port: 8401
      targetPort: 8401