spring:
  cloud:
    gateway:
      routes:
        - id: locations
          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
          predicates:
            - Path=/locations/**          # 프론트는 /locations/** 로 호출
          filters:
            - StripPrefix=1                # 백엔드에는 / 이하만 전달

        - id: notifications
          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

      # CORS – 프론트 개발 시 편의
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"   # TODO : 이후 프론트 주소로 바꾸면됨
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
