spring:
  cloud:
    gateway:
      routes:
        # 1) 비즈니스용 (Authorization 유지)
        - id: locations
          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
          predicates:
            - Path=/api/locations/**
          filters:
            - RewritePath=/api/locations(?<segment>/?.*), ${segment}

        - id: notifications
          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications(?<segment>/?.*), ${segment}

        # 2) 헬스/스웨거 전용 (Authorization 제거)
        - id: locations-actuator-open
          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
          predicates:
            - Path=/api/locations/actuator/**,/api/locations/swagger-ui/**,/api/locations/v3/api-docs/**
          filters:
            - RewritePath=/api/locations(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        - id: notifications-actuator-open
          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
          predicates:
            - Path=/api/notifications/actuator/**,/api/notifications/swagger-ui/**,/api/notifications/v3/api-docs/**
          filters:
            - RewritePath=/api/notifications(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        # ===== TODOS =====
        # 정확히 /api/todos 또는 /api/todos/ 인 경우 -> 백엔드 /todos 로 보냄
        # ===== TODOS (Swagger/Actuator first) =====
        # 1) 공개: /api/todos/actuator/**, /api/todos/swagger-ui/**, /api/todos/v3/api-docs/**
        - id: todos-actuator-open
          order: -1
          uri: http://${TODOS_HOST:todo-service}:${TODOS_PORT:8201}
          predicates:
            - Path=/api/todos/actuator/**,/api/todos/swagger-ui/**,/api/todos/v3/api-docs/**
          filters:
            - RewritePath=/api/todos(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        # 2) 정확히 /api/todos 또는 /api/todos/ -> /todos 로
        - id: todo-service-root
          uri: http://${TODOS_HOST}:${TODOS_PORT}
          predicates:
            - Path=/api/todos,/api/todos/
          filters:
            - SetPath=/todos

        # 3) /api/todos/** -> /todos/** (ID 포함)
        - id: todo-service
          uri: http://${TODOS_HOST}:${TODOS_PORT}
          predicates:
            - Path=/api/todos/**
          filters:
            - RewritePath=/api/todos/(?<segment>.*), /todos/${segment}

        # ===== TRIGGERS =====
        - id: trigger-engine-service
          uri: http://${TRIGGERS_HOST}:${TRIGGERS_PORT}
          predicates:
            - Path=/api/triggers/**
          filters:
            - StripPrefix=2

        - id: triggers-actuator-open
          uri: http://${TRIGGERS_HOST:trigger-engine-service}:${TRIGGERS_PORT:8401}
          predicates:
            - Path=/api/triggers/actuator/**,/api/triggers/swagger-ui/**,/api/triggers/v3/api-docs/**
          filters:
            - RewritePath=/api/triggers(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

      # CORS – 프론트 개발 시 편의
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000" # TODO: 실제 프론트 도메인으로 교체
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
