spring:
  cloud:
    gateway:
      routes:
        # 1) 비즈니스용 (Authorization 유지)
        - id: locations
          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
          predicates:
            - Path=/api/locations/**
          filters:
            - RewritePath=/api/locations(?<segment>/?.*), ${segment}

        - id: notifications
          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications(?<segment>/?.*), ${segment}

        # 2) 헬스/스웨거 전용 (Authorization 제거)
        - id: locations-actuator-open
          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
          predicates:
            - Path=/api/locations/actuator/**,/api/locations/swagger-ui/**,/api/locations/v3/api-docs/**
          filters:
            - RewritePath=/api/locations(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        - id: notifications-actuator-open
          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
          predicates:
            - Path=/api/notifications/actuator/**,/api/notifications/swagger-ui/**,/api/notifications/v3/api-docs/**
          filters:
            - RewritePath=/api/notifications(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        - id: todo-service-root
          uri: http://${TODOS_HOST}:${TODOS_PORT}
          predicates:
            - Path=/api/todos,/api/todos/
          filters:
            - SetPath=/

        - id: todo-service
          uri: http://${TODOS_HOST}:${TODOS_PORT}
          predicates:
            - Path=/api/todos/**
          filters:
            - StripPrefix=2

        - id: trigger-engine-service
          uri: http://${TRIGGERS_HOST}:${TRIGGERS_PORT}
          predicates:
            - Path=/api/triggers/**
          filters:
            - StripPrefix=2

        - id: todos-actuator-open
          uri: http://${TODOS_HOST:todo-service}:${TODOS_PORT:8201}
          predicates:
            - Path=/api/todos/actuator/**,/api/todos/swagger-ui/**,/api/todos/v3/api-docs/**
          filters:
            - RewritePath=/api/todos(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization

        - id: triggers-actuator-open
          uri: http://${TRIGGERS_HOST:trigger-engine-service}:${TRIGGERS_PORT:8401}
          predicates:
            - Path=/api/triggers/actuator/**,/api/triggers/swagger-ui/**,/api/triggers/v3/api-docs/**
          filters:
            - RewritePath=/api/triggers(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Authorization
      #      routes:
      #        - id: locations
      #          uri: http://${LOCATIONS_HOST:location-event-service}:${LOCATIONS_PORT:8301}
      #          predicates:
      #            - Path=/locations/**          # 프론트는 /locations/** 로 호출
      #          filters:
      #            - StripPrefix=1                # 백엔드에는 / 이하만 전달
      #
      #        - id: notifications
      #          uri: http://${NOTIFICATIONS_HOST:notification-service}:${NOTIFICATIONS_PORT:8501}
      #          predicates:
      #            - Path=/notifications/**
      #          filters:
      #            - StripPrefix=1

      # CORS – 프론트 개발 시 편의
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000" # TODO : 이후 프론트 주소로 바꾸면됨
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
