apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: adinga
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api-gateway
          # Jenkins가 이 값을 set image로 최신 태그로 바꿔줄 거야
          image: ghcr.io/2ckdaks/api-gateway:build-0
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: SECURITY_ENABLED
              value: "true"
            - name: SECURITY_DEV_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: dev-token
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: adinga
spec:
  # 처음엔 Ingress 없이 외부 노출을 위해 LoadBalancer로 가자 (EKS/LB, k3s는 클라우드LB 없으니 NodePort로 바꿔도 됨)
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
